name: PlazaApartments
version: '1.0'
main: com.chloespacedout.PlazaApartments.Core
api-version: '1.21'
authors: [ ChloeSpacedOut ]
description: Isolated apartments for the Figura plaza
depend: [WorldGuard]
